name: oacnns
dataset_name: paris_lille_3d
save_dir: results/oacnn_linear_12_paris_lille_3d
dataset_config:
  loops: 1
  voxel_size: 0.1
  voxel_size_preprocessing: 0.05
  grid_overlay: 5
  train_dir: /data/train/
  val_dir: /data/val/
  apply_transforms: True
  grid_overlay: 5
  lambda_p: 12 # either prob for exponent, std for distance in m or range value in meter for radius or box dim
  use_lambda_range: False
  lambda_range: # lambda uniform range between lambda - [0], lambda + [1]
    - 0.4
    - 0.4
  ending: .ply
  sub_cloud_method: linear
  min_appearance: 0.4
  min_pts: 500
  feat_list:
    - disc_coords
train:
  bs: 4
  accumulation_steps: 4
  max_lr:
    - 0.005
  mom: 0.9
  wd: 0.05
  ep: 100
  gamma: 0.98
  clip_gradient: 5
  nr_workers: 0
loss:
  name: cross_entropy
  label_smoothing: 0.05
  weight: null
  ignore_index: -1
  weight_factor: 1.0
model_config:
  in_channels: 3
  nr_classes: 10
  embed_channels: 64
  drop_path_rate: 0.3
  groups:
    - 0
    - 0
    - 0
    - 0
  enc_channels:
    - 64
    - 64
    - 128
    - 256
  enc_depth:
    - 3
    - 3
    - 9
    - 8
  dec_channels:
    - 64
    - 64
    - 128
    - 256
  point_grid_size:
    -
      - 16
      - 32
      - 64
    -
      - 8
      - 16
      - 24
    -
      - 4
      - 8
      - 12
    -
      - 2
      - 4
      - 6
